---
ci_version: &ci_version "${CI_VERSION:-main}"
common_env_vars: &common_env_vars
  BUILD_TYPE: "GDK"
  GDK_BRANCH: "main_branch::${BUILDKITE_BRANCH}"
  PROJECT_BRANCH: "${PROJECT_BRANCH:-match_branch_name_pref::master}"
  USE_FASTBUILD: "${USE_FASTBUILD:-True}"
  IS_BUILDKITE_BUILD: "${IS_BUILDKITE_BUILD:-True}"
  BUILD_ANDROID: "${BUILD_ANDROID:-False}"
  CLEAN_BUILD: "${CLEAN_BUILD:-False}"
  RUN_DEFAULT_TESTS: "${RUN_DEFAULT_TESTS:-True}"
  SLOW_TESTS: "${SLOW_TESTS:-False}"
  EXTRA_TESTS: "${EXTRA_TESTS:-}"
  EXTRA_TESTS_RUN_NATIVE: "${EXTRA_TESTS_RUN_NATIVE:-False}"
  EXTRA_TESTS_RUN_REPGRAPH: "${EXTRA_TESTS_RUN_REPGRAPH:-False}"
  EXTRA_TESTS_RUNS: "${EXTRA_TESTS_RUNS:-1}"

steps:
  # New build pipeline
  # Trigger a 4.27 build
  - trigger: "unrealgdkbuild-ci"
    label: "gdk-ci-4.27"
    async: false
    build:
      branch: *ci_version
      message: "gdk-4.27 ${BUILDKITE_MESSAGE}"
      env:
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_427:-match_branch_name_pref_engine::4.27-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.27"

  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "gdk-ci-4.26"
    async: false
    build:
      branch: *ci_version
      message: "gdk-4.26 ${BUILDKITE_MESSAGE}"
      env:
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_426:-match_branch_name_pref_engine::4.26-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.26"

  # Trigger an Example Project build for any merges into master, preview or release branches of UnrealGDK
  - trigger: "unrealgdkexampleproject-nightly"
    label: "post-merge-example-project-build"
    if: build.env("ENGINE_NET_TEST") != "true" && (build.branch == "master" || build.branch == "preview" || build.branch == "release")
    async: true
    build:
      env:
        NIGHTLY_BUILD: "${NIGHTLY_BUILD:-false}"
        GDK_BRANCH: "${BUILDKITE_BRANCH}"
