---
agent_transients: &agent_transients
  # This is designed to trap and retry failures because agent lost
  # connection. Agent exits with -1 in this case.
  exit_status: -1
  limit: 3

common: &common
  agents:
    - "agent_count=1"
    - "capable_of_building=gdk-for-unreal"
    - "environment=production"
    - "machine_type=quad"  # this name matches to SpatialOS node-size names
    - "platform=windows"
    - "permission_set=builder"
    - "scaler_version=2"
    - "queue=${CI_WINDOWS_BUILDER_QUEUE:-v3-1569490589-f9345a43b21a6cec-------z}"
  retry:
    automatic:
      - <<: *agent_transients
  timeout_in_minutes: 60
  plugins:
    - ca-johnson/taskkill#v4.1: ~

# NOTE: step labels turn into commit-status names like {org}/{repo}/{pipeline}/{step-label}, lower-case and hyphenated.
# These are then relied on to have stable names by other things, so once named, please beware renaming has consequences.

steps:
  - label: "build-GDK-:windows:"
    command: "powershell ./ci/setup-and-build-gdk.ps1 -target_platform Win64"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    artifact_paths:
      - "UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs/*"

  - label: "build-GDK-:linux:"
    command: "powershell ./ci/setup-and-build-gdk.ps1 -target_platform Linux"
    <<: *common # This folds the YAML named anchor into this step. Overrides, if any, should follow, not precede.
    artifact_paths:
      - "UnrealEngine/Engine/Programs/AutomationTool/Saved/Logs/*"

  # Trigger an Example Project build for any merges into master, preview or release branches of UnrealGDK
  - trigger: "unrealgdkexampleproject-nightly"
    label: "Post merge Example Project build"
    branches: "master preview release"
    async: true
    build:
      env:
        GDK_BRANCH="${BUILDKITE_BRANCH}"
