---
ci_version: &ci_version "${CI_VERSION:-1.1}"
common_env_vars: &common_env_vars
  BUILD_TYPE: "GDK"
  GDK_BRANCH: "${BUILDKITE_BRANCH}"
  PROJECT_BRANCH: "${PROJECT_BRANCH:-master}"
  USE_FASTBUILD: "${USE_FASTBUILD:-True}"
  IS_BUILDKITE_BUILD: "${IS_BUILDKITE_BUILD:-True}"
  BUILD_ANDROID: "${BUILD_ANDROID:-False}"
  SKIP_TESTS: "${SKIP_TESTS:-False}"
  CLEAN_BUILD: "${CLEAN_BUILD:-False}"
  SLOW_TESTS: "${SLOW_TESTS}"

steps:
  # New build pipeline
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "gdk-ci-4.26"
    async: false
    build:
      branch: *ci_version
      message: "gdk-4.26 ${BUILDKITE_MESSAGE}"
      env:
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_426:-4.26-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.26"

  # Trigger a 4.25 build
  - trigger: "unrealgdkbuild-ci"
    label: "gdk-ci-4.25"
    async: false
    build:
      branch: *ci_version
      message: "gdk-4.25 ${BUILDKITE_MESSAGE}"
      env:
        <<: *common_env_vars
        ENGINE_BRANCH: "${ENGINE_BRANCH_425:-4.25-SpatialOSUnrealGDK}"
        ENGINE_MAJOR: "4.25"

  # Trigger an Example Project build for any merges into master, preview or release branches of UnrealGDK
  - trigger: "unrealgdkexampleproject-nightly"
    label: "post-merge-example-project-build"
    if: build.env("ENGINE_NET_TEST") != "true" && (build.branch == "master" || build.branch == "preview" || build.branch == "release")
    async: true
    build:
      env:
        NIGHTLY_BUILD: "${NIGHTLY_BUILD:-false}"
        GDK_BRANCH: "${BUILDKITE_BRANCH}"
