---
# This is designed to trap and retry failures because agent lost
# connection. Agent exits with -1 in this case.
agent_transients: &agent_transients
  exit_status: -1
  limit: 3

# BK system error
bk_system_error: &bk_system_error
  exit_status: 255
  limit: 3
  
# Job was interrupted by a signal (e.g. ctrl+c etc)
bk_interrupted_by_signal: &bk_interrupted_by_signal
  exit_status: 15
  limit: 3

# Hook failure
bk_hook_failure: &bk_hook_failure
  exit_status: 127
  limit: 3

steps:
  # New build pipeline
  # Trigger a 4.26 build
  - trigger: "unrealgdkbuild-ci"
    label: "gdk-ci-426 ${BUILDKITE_MESSAGE}"
    async: false
    build: 
      env: 
        BUILD_TYPE: "GDK"
        GDK_BRANCH: "${BUILDKITE_BRANCH}"
        ENGINE_BRANCH: "4.26-SpatialOSUnrealGDK"
        ENGINE_MAJOR: "4.26"
        PROJECT_BRANCH: "master"
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "False"
        SKIP_TESTS: "False"
        CLEAN_BUILD: "False"

  # Trigger a 4.25 build
  - trigger: "unrealgdkbuild-ci"
    label: "gdk-ci-425 ${BUILDKITE_MESSAGE}"
    async: false
    build: 
      env: 
        BUILD_TYPE: "GDK" # GDK or ENGINE
        GDK_BRANCH: "${BUILDKITE_BRANCH}"
        ENGINE_BRANCH: "4.25-SpatialOSUnrealGDK"
        ENGINE_MAJOR: "4.25"
        PROJECT_BRANCH: "master"
        USE_FASTBUILD: "True"
        IS_BUILDKITE_BUILD: "True"
        BUILD_ANDROID: "False"
        SKIP_TESTS: "False"
        CLEAN_BUILD: "False"

  # Trigger an Example Project build for any merges into master, preview or release branches of UnrealGDK
  - trigger: "unrealgdkexampleproject-nightly"
    label: "post-merge-example-project-build"
    if: build.env("ENGINE_NET_TEST") != "true" && (build.branch == "master" || build.branch == "preview" || build.branch == "release")
    async: true
    build:
      env:
        NIGHTLY_BUILD: "${NIGHTLY_BUILD:-false}"
        GDK_BRANCH: "${BUILDKITE_BRANCH}"

# Notify unreal-gdk-builds if there was a failure
notify:
  - slack: 
      channels: 
        - "#unreal-gdk-builds"
      message: "<!subteam^SDB5161M5> Build failure! Please triage and post ticket." # SDB5161M5 is @support-unreal
    if: build.env("BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG") != "unrealgdktestgyms-premerge" && (build.state == "failed" || build.state == "canceled") && build.branch == "master"
    