required=["github.com/2tvenom/go-test-teamcity"]

[[constraint]]
  name = "github.com/klauspost/compress"
  version = "1.2.1"

[[constraint]]
  name = "github.com/spf13/cobra"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"
